using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace Silo.Source;

[Generator]
public class PageAccessGenerator : ISourceGenerator
{
    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxContextReceiver is not BlazorCheckAccessAuthorizedPages receiver)
        { 
            return;
        }

        receiver.Pages = receiver.Pages.Distinct().ToList();

        foreach (var page in receiver.Pages)
        {
            string source = $@"// <auto-generated/>
namespace {page.ContainingNamespace.ToDisplayString()}
{{
    public partial class {page.Name}
    {{
        [CascadingParameter] public TelerikNotification Notification {{ get; set; }}
        [CascadingParameter] public SiloComponentsContext SiloContext {{ get; set; }}

        protected override async Task OnInitializedAsync()
        {{
            if(mustCheckAccess)
            {{
                await CheckAccess();
            }}

            SiloContext.NavbarFilterClicked += () =>
            {{
                IsFiltersShown = !IsFiltersShown;

                StateHasChanged();
            }};

            await SetPageTitle();

            await SiloInitializer();
        }}

        public async Task OnInvalidSubmit(EditContext context)
        {{
            foreach (string validation in context.GetValidationMessages())
            {{
                Notification.Show(validation, ""error"");
            }}
        }}
    }}
}}";

            context.AddSource($"{page.ContainingNamespace.ToDisplayString()}.{page.Name}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new BlazorCheckAccessAuthorizedPages());
    }
}
