<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Silo.Application\Silo.Application.Shared.csproj" />
        <ProjectReference Include="..\Silo.Domains\Silo.Domains.csproj" />
        <ProjectReference Include="..\Silo.Infrastructure.Shared\Silo.Infrastructure.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" />
        <PackageReference Include="Microsoft.Data.SqlClient" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

</Project>
