<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="Serilog.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Silo.Application\Silo.Application.Shared.csproj" />
        <ProjectReference Include="..\Silo.Infrastructure.Shared\Silo.Infrastructure.Shared.csproj" />
        <ProjectReference Include="..\Silo.Shared\Silo.Shared.csproj" />
    </ItemGroup>
</Project>
