using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace Silo.Source.EfCore;

[Generator]
public class EfCoreTriggerConfigurationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register a syntax receiver that finds DbContext classes
        var dbContextClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateDbContext(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // Combine the selected classes with the compilation
        IncrementalValueProvider<(Compilation, ImmutableArray<INamedTypeSymbol?>)> compilationAndClasses
            = context.CompilationProvider.Combine(dbContextClasses.Collect());

        // Generate the source
        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Item1, source.Item2!, spc));
    }

    private static bool IsCandidateDbContext(SyntaxNode node)
    {
        // We're looking for class declarations that might be DbContext
        return node is ClassDeclarationSyntax classDecl
            && classDecl.Identifier.ValueText == "WmsApiContext";
    }

    private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

        if (symbol?.BaseType?.Name != "DbContext")
            return null;

        return symbol;
    }

    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol?> dbContexts, SourceProductionContext context)
    {
        if (dbContexts.IsDefaultOrEmpty)
            return;

        foreach (var dbContext in dbContexts)
        {
            if (dbContext == null)
                continue;

            // Find all DbSet properties to get entity types
            var entityTypes = new System.Collections.Generic.Dictionary<string, INamedTypeSymbol>();
            
            foreach (var member in dbContext.GetMembers())
            {
                if (member is IPropertySymbol property && 
                    property.Type.Name == "DbSet" && 
                    property.Type is INamedTypeSymbol namedType &&
                    namedType.TypeArguments.Length > 0 &&
                    namedType.TypeArguments[0] is INamedTypeSymbol entityType)
                {
                    // Use dictionary to avoid duplicates
                    var key = entityType.ToDisplayString();
                    if (!entityTypes.ContainsKey(key))
                    {
                        entityTypes.Add(key, entityType);
                    }
                }
            }

            var source = GenerateTriggerConfiguration(dbContext, entityTypes);
            context.AddSource($"{dbContext.Name}.TriggerConfiguration.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateTriggerConfiguration(INamedTypeSymbol dbContext, System.Collections.Generic.Dictionary<string, INamedTypeSymbol> entityTypes)
    {
        var namespaceName = dbContext.ContainingNamespace.ToDisplayString();
        var className = dbContext.Name;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");
        sb.AppendLine("        private void ConfigureTriggersFromConfiguration(ModelBuilder modelBuilder)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (configuration is null)");
        sb.AppendLine("            {");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var triggerNamesSection = configuration.GetSection(\"ProjectConfigs:DatabaseConfigs:TriggerNames\");");
        sb.AppendLine();
        sb.AppendLine("            if (triggerNamesSection == null || !triggerNamesSection.GetChildren().Any())");
        sb.AppendLine("            {");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var triggerConfigs = triggerNamesSection.GetChildren();");
        sb.AppendLine();
        sb.AppendLine("            foreach (var triggerConfig in triggerConfigs)");
        sb.AppendLine("            {");
        sb.AppendLine("                var entityName = triggerConfig.Key;");
        sb.AppendLine("                var triggerName = triggerConfig.Value;");
        sb.AppendLine();
        sb.AppendLine("                if (triggerName.HasNoValue())");
        sb.AppendLine("                    continue;");
        sb.AppendLine();
        sb.AppendLine("                // Configure trigger based on entity name");
        sb.AppendLine("                switch (entityName)");
        sb.AppendLine("                {");

        // Generate case statements for each entity
        // Sort by entity name for consistent output
        var sortedEntities = new System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, INamedTypeSymbol>>(entityTypes);
        sortedEntities.Sort((a, b) => string.Compare(a.Value.Name, b.Value.Name, System.StringComparison.Ordinal));

        foreach (var entry in sortedEntities)
        {
            var entityType = entry.Value;
            var entityName = entityType.Name;
            var fullTypeName = entityType.ToDisplayString();

            sb.AppendLine($"                    case \"{entityName}\":");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        var entityBuilder = modelBuilder.Entity<{fullTypeName}>();");
            sb.AppendLine("                        if (triggerName!.Contains(','))");
            sb.AppendLine("                        {");
            sb.AppendLine("                            foreach (var tn in triggerName.Split(','))");
            sb.AppendLine("                            {");
            sb.AppendLine("                                var trimmedTn = tn.Trim();");
            sb.AppendLine("                                if (trimmedTn.HasValue())");
            sb.AppendLine("                                    entityBuilder.ToTable(tb => tb.HasTrigger(trimmedTn));");
            sb.AppendLine("                            }");
            sb.AppendLine("                        }");
            sb.AppendLine("                        else");
            sb.AppendLine("                        {");
            sb.AppendLine("                            entityBuilder.ToTable(tb => tb.HasTrigger(triggerName));");
            sb.AppendLine("                        }");
            sb.AppendLine("                        break;");
            sb.AppendLine("                    }");
            sb.AppendLine();
        }

        sb.AppendLine("                    default:");
        sb.AppendLine("                        System.Diagnostics.Debug.WriteLine($\"Warning: Unknown entity name '{entityName}' in trigger configuration\");");
        sb.AppendLine("                        break;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
