//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silo.Ui.Gate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartUpFlag {
            get {
                return ((int)(this["StartUpFlag"]));
            }
            set {
                this["StartUpFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string SocketPort {
            get {
                return ((string)(this["SocketPort"]));
            }
            set {
                this["SocketPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost:5113")]
        public string ServerIp {
            get {
                return ((string)(this["ServerIp"]));
            }
            set {
                this["ServerIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int TagControlTime {
            get {
                return ((int)(this["TagControlTime"]));
            }
            set {
                this["TagControlTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM6")]
        public string AlarmRelayPort {
            get {
                return ((string)(this["AlarmRelayPort"]));
            }
            set {
                this["AlarmRelayPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string ReaderPower {
            get {
                return ((string)(this["ReaderPower"]));
            }
            set {
                this["ReaderPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MotionDetect {
            get {
                return ((string)(this["MotionDetect"]));
            }
            set {
                this["MotionDetect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Buzzer {
            get {
                return ((string)(this["Buzzer"]));
            }
            set {
                this["Buzzer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Port_Board {
            get {
                return ((string)(this["Port_Board"]));
            }
            set {
                this["Port_Board"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAAAAAAA")]
        public string WM_EPC_Pattern {
            get {
                return ((string)(this["WM_EPC_Pattern"]));
            }
            set {
                this["WM_EPC_Pattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int KindShowProduct {
            get {
                return ((int)(this["KindShowProduct"]));
            }
            set {
                this["KindShowProduct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string GateNumber {
            get {
                return ((string)(this["GateNumber"]));
            }
            set {
                this["GateNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("خروجی سالن تولید")]
        public string GateTitle {
            get {
                return ((string)(this["GateTitle"]));
            }
            set {
                this["GateTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string FromStore {
            get {
                return ((string)(this["FromStore"]));
            }
            set {
                this["FromStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string ToStore {
            get {
                return ((string)(this["ToStore"]));
            }
            set {
                this["ToStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string GateType {
            get {
                return ((string)(this["GateType"]));
            }
            set {
                this["GateType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TagDetectInMultiPart {
            get {
                return ((string)(this["TagDetectInMultiPart"]));
            }
            set {
                this["TagDetectInMultiPart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string IgnoringNonExistentGoods {
            get {
                return ((string)(this["IgnoringNonExistentGoods"]));
            }
            set {
                this["IgnoringNonExistentGoods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AtentionForNotRegisteredTag {
            get {
                return ((string)(this["AtentionForNotRegisteredTag"]));
            }
            set {
                this["AtentionForNotRegisteredTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string ReaderConnectDetails {
            get {
                return ((string)(this["ReaderConnectDetails"]));
            }
            set {
                this["ReaderConnectDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ReaderType {
            get {
                return ((string)(this["ReaderType"]));
            }
            set {
                this["ReaderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ReaderConnectionType {
            get {
                return ((string)(this["ReaderConnectionType"]));
            }
            set {
                this["ReaderConnectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("انبار محصول")]
        public string FromStoreTitle {
            get {
                return ((string)(this["FromStoreTitle"]));
            }
            set {
                this["FromStoreTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("فروش رفته")]
        public string ToStoreTitle {
            get {
                return ((string)(this["ToStoreTitle"]));
            }
            set {
                this["ToStoreTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartActionKind {
            get {
                return ((string)(this["StartActionKind"]));
            }
            set {
                this["StartActionKind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartActionDetails {
            get {
                return ((string)(this["StartActionDetails"]));
            }
            set {
                this["StartActionDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EndActionKind {
            get {
                return ((string)(this["EndActionKind"]));
            }
            set {
                this["EndActionKind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EndActionDetails {
            get {
                return ((string)(this["EndActionDetails"]));
            }
            set {
                this["EndActionDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DetectANDSaveMachin {
            get {
                return ((string)(this["DetectANDSaveMachin"]));
            }
            set {
                this["DetectANDSaveMachin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SearchMachin {
            get {
                return ((string)(this["SearchMachin"]));
            }
            set {
                this["SearchMachin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MachinType {
            get {
                return ((int)(this["MachinType"]));
            }
            set {
                this["MachinType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ControlByDocument {
            get {
                return ((string)(this["ControlByDocument"]));
            }
            set {
                this["ControlByDocument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string GetDocumentFromProductInfo {
            get {
                return ((string)(this["GetDocumentFromProductInfo"]));
            }
            set {
                this["GetDocumentFromProductInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string RequirmentDocument {
            get {
                return ((string)(this["RequirmentDocument"]));
            }
            set {
                this["RequirmentDocument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string GetInventorySummaryByStoreCode {
            get {
                return ((string)(this["GetInventorySummaryByStoreCode"]));
            }
            set {
                this["GetInventorySummaryByStoreCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AtentionForFreezedTag {
            get {
                return ((string)(this["AtentionForFreezedTag"]));
            }
            set {
                this["AtentionForFreezedTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AtentionForNotQCTag {
            get {
                return ((string)(this["AtentionForNotQCTag"]));
            }
            set {
                this["AtentionForNotQCTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int KindGateSave {
            get {
                return ((int)(this["KindGateSave"]));
            }
            set {
                this["KindGateSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TrueRelayDetails1 {
            get {
                return ((string)(this["TrueRelayDetails1"]));
            }
            set {
                this["TrueRelayDetails1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TrueRelayDetails2 {
            get {
                return ((string)(this["TrueRelayDetails2"]));
            }
            set {
                this["TrueRelayDetails2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TrueRelayDetails3 {
            get {
                return ((string)(this["TrueRelayDetails3"]));
            }
            set {
                this["TrueRelayDetails3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TrueRelay {
            get {
                return ((string)(this["TrueRelay"]));
            }
            set {
                this["TrueRelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string UserAccessForDeleteTrueSerial {
            get {
                return ((string)(this["UserAccessForDeleteTrueSerial"]));
            }
            set {
                this["UserAccessForDeleteTrueSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string UserAccessForDeleteErrorSerial {
            get {
                return ((string)(this["UserAccessForDeleteErrorSerial"]));
            }
            set {
                this["UserAccessForDeleteErrorSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ProductValueImportant {
            get {
                return ((string)(this["ProductValueImportant"]));
            }
            set {
                this["ProductValueImportant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string AtentionForWithOutQCTag {
            get {
                return ((string)(this["AtentionForWithOutQCTag"]));
            }
            set {
                this["AtentionForWithOutQCTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string IgnoringTagAgeThenLess {
            get {
                return ((string)(this["IgnoringTagAgeThenLess"]));
            }
            set {
                this["IgnoringTagAgeThenLess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string IgnoringTagAgeThenLessDetails {
            get {
                return ((string)(this["IgnoringTagAgeThenLessDetails"]));
            }
            set {
                this["IgnoringTagAgeThenLessDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string GetTagFromHandheld {
            get {
                return ((string)(this["GetTagFromHandheld"]));
            }
            set {
                this["GetTagFromHandheld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string PlaySoundForAlarm {
            get {
                return ((string)(this["PlaySoundForAlarm"]));
            }
            set {
                this["PlaySoundForAlarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string PlaySoundForConfirm {
            get {
                return ((string)(this["PlaySoundForConfirm"]));
            }
            set {
                this["PlaySoundForConfirm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TrueRelayDetails4 {
            get {
                return ((string)(this["TrueRelayDetails4"]));
            }
            set {
                this["TrueRelayDetails4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlarmRelayDetails1 {
            get {
                return ((string)(this["AlarmRelayDetails1"]));
            }
            set {
                this["AlarmRelayDetails1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlarmRelayDetails2 {
            get {
                return ((string)(this["AlarmRelayDetails2"]));
            }
            set {
                this["AlarmRelayDetails2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlarmRelayDetails3 {
            get {
                return ((string)(this["AlarmRelayDetails3"]));
            }
            set {
                this["AlarmRelayDetails3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlarmRelayDetails4 {
            get {
                return ((string)(this["AlarmRelayDetails4"]));
            }
            set {
                this["AlarmRelayDetails4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlarmRelay {
            get {
                return ((string)(this["AlarmRelay"]));
            }
            set {
                this["AlarmRelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ChangeReaderPowerTools {
            get {
                return ((string)(this["ChangeReaderPowerTools"]));
            }
            set {
                this["ChangeReaderPowerTools"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IgnoreSerials {
            get {
                return ((string)(this["IgnoreSerials"]));
            }
            set {
                this["IgnoreSerials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ChangeDocumentStatusAfterCheck {
            get {
                return ((string)(this["ChangeDocumentStatusAfterCheck"]));
            }
            set {
                this["ChangeDocumentStatusAfterCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string AppReset {
            get {
                return ((string)(this["AppReset"]));
            }
            set {
                this["AppReset"] = value;
            }
        }
    }
}
