<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Identity.Core" />
        <PackageReference Include="Microsoft.Extensions.Identity.Stores" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
        <PackageReference Include="Microsoft.JSInterop" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Silo.Application\Silo.Application.Shared.csproj" />
        <ProjectReference Include="..\Silo.Infrastructure.Web\Silo.Infrastructure.Web.csproj" />
        <ProjectReference Include="..\Silo.Shared\Silo.Shared.csproj" />
    </ItemGroup>

</Project>
