CREATE TABLE [dbo].[tbl_Print] (
    [Id]                     INT             IDENTITY (1, 1) NOT NULL,
    [ProductSerial]          NVARCHAR (50)   NULL,
    [ProductCode]            NVARCHAR (50)   NULL,
    [ProductName]            NVARCHAR (500)  NULL,
    [ProductDescription]     NVARCHAR (300)  NULL,
    [ProductType]            NVARCHAR (50)   NULL,
    [ProductCount]           DECIMAL (18, 2) NULL,
    [ProductItemCount]       DECIMAL (18, 2) NULL,
    [ProductCountInPack]     DECIMAL (18, 2) NULL,
    [ProductUnit]            NVARCHAR (50)   NULL,
    [ProductSize]            NVARCHAR (50)   NULL,
    [ProductRegCode]         NVARCHAR (50)   NULL,
    [ProductWeight]          DECIMAL (18, 2) NULL,
    [ProductVolume]          DECIMAL (18, 2) NULL,
    [ProductStatus]          NVARCHAR (50)   NULL,
    [ProjectCode]            NVARCHAR (50)   NULL,
    [TagEpc]                 NVARCHAR (50)   NULL,
    [ProductProductionShift] NVARCHAR (50)   NULL,
    [ProductProductionLine]  NVARCHAR (50)   NULL,
    [ProductContractType]    INT             NULL,
    [PackageId]              INT             NULL,
    [Location]               NVARCHAR (50)   NULL,
    [PrintActionId]          INT             NULL,
    [PrintType]              NVARCHAR (50)   NULL,
    [PrintActionDateTime]    DATETIME        NULL,
    [PrintUser]              NVARCHAR (50)   NULL,
    [PrintFlag]              INT             NULL,
    [RegisterActionDateTime] DATETIME        NULL,
    [RegisterFlag]           INT             NULL,
    [RegisterType]           INT             NULL,
    [InputFileName]          NVARCHAR (50)   NULL,
    [ErrorTime]              NVARCHAR (50)   NULL,
    [ErrorDesc]              NVARCHAR (200)  NULL,
    [SoftDelete]             INT             NULL,
    [ReRegister]             BIT             NULL,
    [PrintQueue]             BIT             NULL,
    [DocumentId]             NVARCHAR (50)   NULL,
    [DocumentItemId]         NVARCHAR (50)   NULL,
    [offline_epc]            NVARCHAR (50)   CONSTRAINT [DF__tbl_Print__offli__6383C8BA] DEFAULT (N'0') NULL,
    [offline_reg_status]     INT             CONSTRAINT [DF__tbl_Print__offli__6477ECF3] DEFAULT ((0)) NULL,
    [offline_regDate]        NVARCHAR (10)   CONSTRAINT [DF__tbl_Print__offli__656C112C] DEFAULT (N'0') NULL,
    [RegisterUser]           NVARCHAR (50)   NULL,
    [RegisterDate]           NVARCHAR (50)   NULL,
    [Manufacturer]           NVARCHAR (50)   NULL,
    [AntiFire]               NVARCHAR (50)   NULL,
    [DestinationCode]        NVARCHAR (50)   NULL,
    [SoftDeleteUser]         NVARCHAR (50)   NULL,
    [SoftDeleteDate]         NVARCHAR (50)   NULL,
    [fld_ProductGroup]       NVARCHAR (128)  NULL,
    [fld_ProductBrand]       NVARCHAR (128)  NULL,
    [ProductProperties]      NVARCHAR (MAX)  NULL,
    [ProductOldSerial]       NVARCHAR (128)  NULL,
    [fld_ProductSubGroup]       NVARCHAR (128)  NULL,
    [fld_ProductClass]       NVARCHAR (128)  NULL, 
    [TagEpc2] NVARCHAR(128) NULL,
);
