CREATE TABLE [dbo].[tbl_PlacementOrders] (
    [id]                    INT            IDENTITY (1, 1) NOT NULL,
    [fld_POCode]            INT            NULL,
    [fld_POUser]            NVARCHAR (50)  NULL,
    [fld_PODateTime]        DATETIME       NULL,
    [fld_POProductSerial]   NVARCHAR (MAX) NULL,
    [fld_POProductCode]     NVARCHAR (MAX) NULL,
    [fld_POType]            INT            NULL,
    [fld_POPackCount]       DECIMAL(18, 2) NULL,
    [fld_POExpireDate]      DATETIME       NULL,
    [fld_POStatus]          INT            NULL,
    [fld_POFromStoreCode]   NVARCHAR (MAX) NULL,
    [fld_POFromZoneCode]    NVARCHAR (MAX) NULL,
    [fld_POToStoreCode]     NVARCHAR (MAX) NULL,
    [fld_POStoreCode]       NVARCHAR (MAX) NULL,
    [fld_POZoneCode]        NVARCHAR (MAX) NULL,
    [fld_POFromDateTime]    DATETIME       NULL,
    [fld_POToDateTime]      DATETIME       NULL,
    [fld_POPackCountRemain] INT            NULL,
    [fld_POProductLine]     NVARCHAR (50)  NULL,
    [fld_POProductShift]    NVARCHAR (50)  NULL,
    [fld_POWMDriverId]      NVARCHAR (MAX) NULL,
    [fld_PODocumentKey]     NVARCHAR (450) NULL,
    [fld_PODocumentType]    NVARCHAR (50)  NULL,
    [fld_POSumValue]        decimal(18, 2) NULL, 
    [fld_POParent] INT NULL, 
    [fld_POPackCountDescription] NVARCHAR(100) NULL
);

