CREATE TABLE [dbo].[tbl_TruckCross] (
    [fld_TruckCrossId]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [fld_TruckCrossPlaque]            NVARCHAR (20)   NULL,
    [fld_TruckCrossInternationalPlaque]  NVARCHAR (20)   NULL,
    [fld_TruckCrossDriverName]        NVARCHAR (50)   NULL,
    [fld_TruckCrossDriverPhone]       NVARCHAR (20)   NULL,
    [fld_TruckCrossNationalCode]      NVARCHAR (20)   NOT NULL,
    [fld_TruckCrossPassportCode]      NVARCHAR (50)   NULL,
    [fld_TruckCrossCompany]           INT             NULL,
    [fld_TruckCrossSerial]            NVARCHAR (50)   NULL,
    [fld_TruckCrossLicenseCode]       NVARCHAR (50)   NULL,
    [fld_TruckCrossType]              INT             NULL,
    [fld_TruckCrossTypeDesc]          NVARCHAR (256)  NULL,
    [fld_TruckCrossStatus]            INT             NULL,
    [fld_TruckCrossPresentOperationType]  INT         NULL,
    [fld_TruckCrossPresentOperationDestination]  INT  NULL,
    [fld_TruckCrossPresentShipment]   INT             NULL,
    [fld_TruckCrossPresentShipmentNumber] NVARCHAR (50) NULL,
    [fld_TruckCrossPresentCustomer]   INT             NULL,
    [fld_TruckCrossPresentCause]      INT             NULL,
    [fld_TruckCrossPresentTurn]       INT             NULL,
    [fld_TruckCrossPresentDateTime]   DATETIME        NULL,
    [fld_TruckCrossPresentDesc]       NVARCHAR (250)  NULL,
    [fld_TruckCrossPresentUserId]     NVARCHAR (128)  NULL,
    [fld_TruckCrossPresentRevokeDateTime]	datetime	NULL,
    [fld_TruckCrossPresentRevokeUserId]	nvarchar(128)	NULL,
    [fld_TruckCrossEnterDateTime]     DATETIME        NULL,
    [fld_TruckCrossEnterWeightTonage] DECIMAL (18, 2) NULL,
    [fld_TruckCrossEnterDesc]         NVARCHAR (250)  NULL,
    [fld_TruckCrossEnterEpc]          NVARCHAR (128)  NULL,
    [fld_TruckCrossEnterOtherEpcs]    NVARCHAR (250)  NULL,
    [fld_TruckCrossEnterUserId]       NVARCHAR (128)  NULL,
    [fld_TruckCrossEnterAcceptor]     NVARCHAR (50)   NULL,
    [fld_TruckCrossEnterAcceptPlace]  INT             NULL,
    [fld_TruckCrossExitDateTime]      DATETIME        NULL,
    [fld_TruckCrossExitUserId]        NVARCHAR (128)  NULL,
    [fld_TruckCrossExitGateId]        INT             NULL,
    [fld_TruckCrossExitWeightTonage]  DECIMAL (18, 2) NULL,
    [fld_TruckCrossExitDesc]          NVARCHAR (250)  NULL,
    [fld_TruckCrossExitDestination]   NVARCHAR (128)  NULL,
    [fld_TruckCrossExitPureWeightCargo] DECIMAL (18, 2) NULL,
    [fld_TruckCrossExitWeightbridgeReceiptNumber] NVARCHAR (50)   NULL,
    [fld_TruckCrossExitCargoOwnerName] NVARCHAR (50)  NULL,
    [fld_TruckCrossExitCargoOwnerPhone] NVARCHAR (50) NULL,
    [fld_TruckCrossExitDeliveryAddress] NVARCHAR (250) NULL,
    [fld_TruckCrossExitShipmentCost]  NVARCHAR (MAX)   NULL,
    [fld_TruckCrossExitPaymentType]   INT             NULL,
    [fld_TruckCrossExitUnitPrice]     NVARCHAR (50)   NULL,
    [fld_TruckCrossExitTotalCost]     NVARCHAR (50)   NULL,
    [fld_TruckCrossExitDistance]     NVARCHAR (50)   NULL, 
    [fld_TruckCrossDynamicFields] NVARCHAR(MAX) NULL
);

