CREATE TABLE [dbo].[tbl_Products] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [ProductCode]          NVARCHAR (50)   NOT NULL,
    [ProductTitle]         NVARCHAR (250)  NULL,
    [ProductENTitle]       NVARCHAR (250)  NULL,
    [ProductPackValue]     DECIMAL (18, 2) NULL,
    [ProductPackWeight]    DECIMAL (18, 2) NULL,
    [ProductPackVolume]    DECIMAL (18, 2) NULL,
    [ProductCountInPack]   DECIMAL (18, 2) NULL,
    [ProductValue]         DECIMAL (18, 2) NULL,
    [ProductTechnicalCode] NVARCHAR (50)   NULL,
    [ProductProperties]    NVARCHAR (MAX)  NULL,
    [ProductType]          NVARCHAR (50)   NULL,
    [ProductStatus]        NVARCHAR (50)   NULL,
    [ProductSize]          NVARCHAR (50)   NULL,
    [ProductUnit]          NVARCHAR (50)   NULL,
    [ProductRegUser]       NVARCHAR (50)   NULL,
    [ProductRegDateTime]   DATETIME        NULL,
    [ProductGalleryId]     INT   ,
    [ProductTechnicalData] NVARCHAR (MAX)  NULL,
    [fld_ProductGroup]     NVARCHAR (128)  NULL,
    [fld_ProductBrand]     NVARCHAR (128)  NULL, 
    [fld_ProductSubGroup]       NVARCHAR (128)  NULL,
    [fld_ProductClass]          NVARCHAR (128)  NULL,
    [fld_ProductGuaranteeType] INT NULL, 
    [fld_ProductGuaranteeDays] INT NULL, 
    [fld_ProductExpireType] INT NULL, 
    [fld_ProductExpireDays] INT NULL, 
    [fld_ProductIsActive] BIT NULL DEFAULT 1, 
    [fld_ProductGuaranteeEndDate] NVARCHAR(10) NULL, 
    [fld_ProductExpireEndDate] NVARCHAR(10) NULL, 
    [fld_ProductGuaranteeMonths] INT NULL, 
    [fld_ProductExpireMonths] INT NULL, 
    [fld_HasDoubleTag] BIT NULL DEFAULT 0
);

